#!/usr/bin/env bash
# tools/clean-workspace.sh
# TicketVision workspace scrubber
# - Safe defaults: cleans Python + test/build/cache artifacts
# - Optional: pass --js to also prune node_modules & Vite dist (big!)
# - Optional: --dry-run to preview deletions
#
# Usage:
#   bash tools/clean-workspace.sh
#   bash tools/clean-workspace.sh --dry-run
#   bash tools/clean-workspace.sh --js
#   bash tools/clean-workspace.sh --js --dry-run
#
# Notes:
# - Works on macOS default /bin/bash (no mapfile), spaces-safe (-print0).

set -euo pipefail

DRY_RUN=0
CLEAN_JS=0

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --js)      CLEAN_JS=1 ;;
    *) echo "Unknown arg: $arg" >&2; exit 2 ;;
  esac
done

run_rm() {
  # $1: path to remove
  if [ "$DRY_RUN" -eq 1 ]; then
    echo "[dry-run] rm -rf -- \"$1\""
  else
    rm -rf -- "$1"
  fi
}

echo "➤ Cleaning Python bytecode & caches…"
# __pycache__, *.pyc, *.pyo  (safe to delete) — Python will regenerate as needed.
# ref: Python caches are disposable.  [oai_citation:0‡realpython.com](https://realpython.com/python-pycache/?utm_source=chatgpt.com)
find . -name "__pycache__" -type d -print0 | while IFS= read -r -d '' d; do run_rm "$d"; done
find . \( -name "*.pyc" -o -name "*.pyo" \) -type f -print0 | while IFS= read -r -d '' f; do run_rm "$f"; done

echo "➤ Cleaning test/tool caches…"
# pytest cache directory (disposable)  [oai_citation:1‡Pytest Documentation](https://docs.pytest.org/en/stable/reference/customize.html?utm_source=chatgpt.com)
find . -name ".pytest_cache" -type d -print0 | while IFS= read -r -d '' d; do run_rm "$d"; done
# mypy cache (disposable; will be re-created)  [oai_citation:2‡mypy Documentation](https://mypy.readthedocs.io/en/stable/command_line.html?utm_source=chatgpt.com)
find . -name ".mypy_cache" -type d -print0 | while IFS= read -r -d '' d; do run_rm "$d"; done
# ruff cache
find . -name ".ruff_cache" -type d -print0 | while IFS= read -r -d '' d; do run_rm "$d"; done

echo "➤ Cleaning coverage artifacts…"
find . -name "htmlcov" -type d -print0           | while IFS= read -r -d '' d; do run_rm "$d"; done
find . -name ".coverage" -type f -print0         | while IFS= read -r -d '' f; do run_rm "$f"; done
find . -name "coverage.xml" -type f -print0      | while IFS= read -r -d '' f; do run_rm "$f"; done

echo "➤ Cleaning build artifacts…"
# Generic Python/packaging build outputs
find . -name "build" -type d -print0             | while IFS= read -r -d '' d; do run_rm "$d"; done
find . -name "dist" -type d -print0              | while IFS= read -r -d '' d; do run_rm "$d"; done
find . -name "*.egg-info" -type d -print0        | while IFS= read -r -d '' d; do run_rm "$d"; done

echo "➤ Cleaning editor/OS junk…"
find . -name ".DS_Store" -type f -print0         | while IFS= read -r -d '' f; do run_rm "$f"; done
find . -name "Thumbs.db" -type f -print0         | while IFS= read -r -d '' f; do run_rm "$f"; done

echo "➤ Cleaning temporary & backup files…"
find . \( -name "*.tmp" -o -name "*.temp" -o -name "*.log" -o -name "*.bak" -o -name "*.orig" \) \
     -type f -print0 | while IFS= read -r -d '' f; do run_rm "$f"; done

# Clean stray compiled notebooks caches (if any)
find . -name ".ipynb_checkpoints" -type d -print0 | while IFS= read -r -d '' d; do run_rm "$d"; done

if [ "$CLEAN_JS" -eq 1 ]; then
  echo "➤ Cleaning Node/Vite artifacts (node_modules, web/*/dist)…"
  # node_modules can be deleted; will be reinstalled from lockfiles (npm/pnpm/yarn).  [oai_citation:3‡Stack Overflow](https://stackoverflow.com/questions/65527753/what-will-happen-if-i-delete-node-modules-folder?utm_source=chatgpt.com)
  find . -type d -name "node_modules" -prune -print0 | while IFS= read -r -d '' d; do run_rm "$d"; done
  # Vite build outputs are disposable (regenerated by `vite build`).  [oai_citation:4‡vitejs](https://vite.dev/guide/build?utm_source=chatgpt.com)
  find ./tvx-web -type d -name "dist" -print0 2>/dev/null | while IFS= read -r -d '' d; do run_rm "$d"; done
fi

echo "➤ Pruning empty __pycache__ or cache dirs (if any left)…"
find . -type d \( -name "__pycache__" -o -name ".pytest_cache" -o -name ".mypy_cache" -o -name ".ruff_cache" \) \
  -empty -print0 | while IFS= read -r -d '' d; do run_rm "$d"; done

echo "✅ Done."
if [ "$DRY_RUN" -eq 1 ]; then
  echo "NOTE: This was a dry run. Re-run without --dry-run to actually delete."
fi
if [ "$CLEAN_JS" -eq 0 ]; then
  echo "TIP: Add --js to also remove node_modules/ and Vite dist/ (can free many GB)."
fi
